// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-_1FceeSl-uIFNCBcsJE-Q8tNf8gUAtU',
    appId: '1:730068579652:web:36cb1b9618aa042a7d1311',
    messagingSenderId: '730068579652',
    projectId: 'todolist-app-v2',
    authDomain: 'todolist-app-v2.firebaseapp.com',
    storageBucket: 'todolist-app-v2.appspot.com',
    measurementId: 'G-TFE8B6BL8R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY89oZwnOUlyW_N8qUXQf7gM3Wur0MNkg',
    appId: '1:730068579652:android:fc106042fdd357a67d1311',
    messagingSenderId: '730068579652',
    projectId: 'todolist-app-v2',
    storageBucket: 'todolist-app-v2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5OF6Prs-FntTQb5HNIoqwe6oKEWw8NAk',
    appId: '1:730068579652:ios:a9ea3b972c0618007d1311',
    messagingSenderId: '730068579652',
    projectId: 'todolist-app-v2',
    storageBucket: 'todolist-app-v2.appspot.com',
    iosBundleId: 'br.com.todolistappv2.todolistAppV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5OF6Prs-FntTQb5HNIoqwe6oKEWw8NAk',
    appId: '1:730068579652:ios:a9ea3b972c0618007d1311',
    messagingSenderId: '730068579652',
    projectId: 'todolist-app-v2',
    storageBucket: 'todolist-app-v2.appspot.com',
    iosBundleId: 'br.com.todolistappv2.todolistAppV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-_1FceeSl-uIFNCBcsJE-Q8tNf8gUAtU',
    appId: '1:730068579652:web:b42411e8c29972a77d1311',
    messagingSenderId: '730068579652',
    projectId: 'todolist-app-v2',
    authDomain: 'todolist-app-v2.firebaseapp.com',
    storageBucket: 'todolist-app-v2.appspot.com',
    measurementId: 'G-NFX1B6LFS3',
  );
}
